/**
 * Canonical catalogue of Subscriby webhook events exposed by this package.
 *
 * Single source of truth — imported by SubscribyTrigger.node.ts and by the
 * README generation process. When Subscriby adds a new event, update this
 * file only; the trigger node multiOptions list and README events table both
 * derive from it.
 *
 * Event names mirror the catalogue published at
 * https://docs.subscriby.net/webhooks/event-reference.
 */
export const EVENT_CATALOG = [
  { family: 'Access Code', name: 'Access Code — Expired', value: 'access_code.expired' },
  { family: 'Access Code', name: 'Access Code — Generated', value: 'access_code.generated' },
  { family: 'Access Code', name: 'Access Code — Redeemed', value: 'access_code.redeemed' },
  { family: 'Billing', name: 'Billing — Account Locked', value: 'billing.account_locked' },
  { family: 'Billing', name: 'Billing — Grace Period Warning', value: 'billing.grace_period_warning' },
  { family: 'Billing', name: 'Billing — Invoice Created', value: 'billing.invoice_created' },
  { family: 'Billing', name: 'Billing — Invoice Overdue', value: 'billing.invoice_overdue' },
  { family: 'Billing', name: 'Billing — Invoice Paid', value: 'billing.invoice_paid' },
  { family: 'Billing', name: 'Billing — Payment Failed', value: 'billing.payment_failed' },
  { family: 'Billing', name: 'Billing — Tier Cancelled', value: 'billing.tier_cancelled' },
  { family: 'Billing', name: 'Billing — Tier Downgraded', value: 'billing.tier_downgraded' },
  { family: 'Billing', name: 'Billing — Tier Upgraded', value: 'billing.tier_upgraded' },
  { family: 'Billing', name: 'Billing — Trial Ending', value: 'billing.trial_ending' },
  { family: 'Broadcast', name: 'Broadcast — Completed', value: 'broadcast.completed' },
  { family: 'Broadcast', name: 'Broadcast — Queued', value: 'broadcast.queued' },
  { family: 'Coupon', name: 'Coupon — Activated', value: 'coupon.activated' },
  { family: 'Coupon', name: 'Coupon — Created', value: 'coupon.created' },
  { family: 'Coupon', name: 'Coupon — Deactivated', value: 'coupon.deactivated' },
  { family: 'Coupon', name: 'Coupon — Deleted', value: 'coupon.deleted' },
  { family: 'Coupon', name: 'Coupon — Exhausted', value: 'coupon.exhausted' },
  { family: 'Coupon', name: 'Coupon — Redeemed', value: 'coupon.redeemed' },
  { family: 'Coupon', name: 'Coupon — Updated', value: 'coupon.updated' },
  { family: 'Group', name: 'Group — Created', value: 'group.created' },
  { family: 'Group', name: 'Group — Deleted', value: 'group.deleted' },
  { family: 'Group', name: 'Group — Members Synced', value: 'group.members_synced' },
  { family: 'Group', name: 'Group — Updated', value: 'group.updated' },
  { family: 'Member', name: 'Member — Banned', value: 'member.banned' },
  { family: 'Member', name: 'Member — Churned', value: 'member.churned' },
  { family: 'Member', name: 'Member — Converted', value: 'member.converted' },
  { family: 'Member', name: 'Member — Joined', value: 'member.joined' },
  { family: 'Member', name: 'Member — Kicked', value: 'member.kicked' },
  { family: 'Member', name: 'Member — Removed', value: 'member.removed' },
  { family: 'Member', name: 'Member — Resource Added', value: 'member.resource_added' },
  { family: 'Member', name: 'Member — Resource Removed', value: 'member.resource_removed' },
  { family: 'Member', name: 'Member — Trial Joined', value: 'member.trial_joined' },
  { family: 'Member', name: 'Member — Unbanned', value: 'member.unbanned' },
  { family: 'Pass', name: 'Pass — Holder Missed', value: 'pass.holder_missed' },
  { family: 'Pass', name: 'Pass — Holder Moved', value: 'pass.holder_moved' },
  { family: 'Pass', name: 'Pass — Holder Queued', value: 'pass.holder_queued' },
  { family: 'Pass', name: 'Pass — Holder Stranded', value: 'pass.holder_stranded' },
  { family: 'Pass', name: 'Pass — Window Cancelled', value: 'pass.window_cancelled' },
  { family: 'Pass', name: 'Pass — Window Closed', value: 'pass.window_closed' },
  { family: 'Pass', name: 'Pass — Window Opened', value: 'pass.window_opened' },
  { family: 'Pass', name: 'Pass — Window Scheduled', value: 'pass.window_scheduled' },
  { family: 'Pass Series', name: 'Pass Series — Completed', value: 'pass_series.completed' },
  { family: 'Pass Series', name: 'Pass Series — Pass Added', value: 'pass_series.leg_added' },
  { family: 'Pass Series', name: 'Pass Series — Pass Completed', value: 'pass_series.leg_completed' },
  { family: 'Pass Series', name: 'Pass Series — Pass Dropped', value: 'pass_series.leg_dropped' },
  { family: 'Pass Series', name: 'Pass Series — Pass Substituted', value: 'pass_series.leg_substituted' },
  { family: 'Pass Series', name: 'Pass Series — Presale Opened', value: 'pass_series.presale_opened' },
  { family: 'Pass Series', name: 'Pass Series — Purchased', value: 'pass_series.purchased' },
  { family: 'Pass Series', name: 'Pass Series — Seats Exhausted', value: 'pass_series.seats_exhausted' },
  { family: 'Payment', name: 'Payment — Failed', value: 'payment.failed' },
  { family: 'Payment', name: 'Payment — Pending', value: 'payment.pending' },
  { family: 'Payment', name: 'Payment — Refunded', value: 'payment.refunded' },
  { family: 'Payment', name: 'Payment — Succeeded', value: 'payment.succeeded' },
  { family: 'Plan', name: 'Plan — Activated', value: 'plan.activated' },
  { family: 'Plan', name: 'Plan — Created', value: 'plan.created' },
  { family: 'Plan', name: 'Plan — Deactivated', value: 'plan.deactivated' },
  { family: 'Plan', name: 'Plan — Deleted', value: 'plan.deleted' },
  { family: 'Plan', name: 'Plan — Sync Completed', value: 'plan.sync_completed' },
  { family: 'Plan', name: 'Plan — Updated', value: 'plan.updated' },
  { family: 'Project', name: 'Project — Archived', value: 'project.archived' },
  { family: 'Project', name: 'Project — Bot Connected', value: 'project.bot.connected' },
  { family: 'Project', name: 'Project — Bot Disconnected', value: 'project.bot.disconnected' },
  { family: 'Project', name: 'Project — Bot Status Changed', value: 'project.bot.status_changed' },
  { family: 'Project', name: 'Project — Created', value: 'project.created' },
  { family: 'Project', name: 'Project — Deleted', value: 'project.deleted' },
  { family: 'Project', name: 'Project — Restored', value: 'project.restored' },
  { family: 'Project', name: 'Project — Updated', value: 'project.updated' },
  { family: 'Project Resource', name: 'Project Resource — Created', value: 'project.resource.created' },
  { family: 'Project Resource', name: 'Project Resource — Deleted', value: 'project.resource.deleted' },
  { family: 'Project Resource', name: 'Project Resource — Linked', value: 'project.resource.linked' },
  { family: 'Project Resource', name: 'Project Resource — Status Changed', value: 'project.resource.status_changed' },
  { family: 'Project Resource', name: 'Project Resource — Unlinked', value: 'project.resource.unlinked' },
  { family: 'Project Resource', name: 'Project Resource — Updated', value: 'project.resource.updated' },
  { family: 'Project Payment Method', name: 'Project Payment Method — Deleted', value: 'project.payment_method.deleted' },
  { family: 'Project Payment Method', name: 'Project Payment Method — Updated', value: 'project.payment_method.updated' },
  { family: 'Role', name: 'Role — Created', value: 'role.created' },
  { family: 'Role', name: 'Role — Deleted', value: 'role.deleted' },
  { family: 'Role', name: 'Role — Updated', value: 'role.updated' },
  { family: 'Subscription', name: 'Subscription — Activated', value: 'subscription.activated' },
  { family: 'Subscription', name: 'Subscription — Cancelled', value: 'subscription.cancelled' },
  { family: 'Subscription', name: 'Subscription — Created', value: 'subscription.created' },
  { family: 'Subscription', name: 'Subscription — Downgraded', value: 'subscription.downgraded' },
  { family: 'Subscription', name: 'Subscription — Expired', value: 'subscription.expired' },
  { family: 'Subscription', name: 'Subscription — Past Due', value: 'subscription.past_due' },
  { family: 'Subscription', name: 'Subscription — Paused', value: 'subscription.paused' },
  { family: 'Subscription', name: 'Subscription — Reactivated', value: 'subscription.reactivated' },
  { family: 'Subscription', name: 'Subscription — Refunded', value: 'subscription.refunded' },
  { family: 'Subscription', name: 'Subscription — Renewed', value: 'subscription.renewed' },
  { family: 'Subscription', name: 'Subscription — Trial Converting', value: 'subscription.trial_converting' },
  { family: 'Subscription', name: 'Subscription — Trial Expired', value: 'subscription.trial_expired' },
  { family: 'Subscription', name: 'Subscription — Trial Started', value: 'subscription.trial_started' },
  { family: 'Subscription', name: 'Subscription — Unpaid', value: 'subscription.unpaid' },
  { family: 'Subscription', name: 'Subscription — Unpaused', value: 'subscription.unpaused' },
  { family: 'Subscription', name: 'Subscription — Upgraded', value: 'subscription.upgraded' },
  { family: 'Support', name: 'Support — Canned Reply Created', value: 'support.canned_reply.created' },
  { family: 'Support', name: 'Support — Canned Reply Deleted', value: 'support.canned_reply.deleted' },
  { family: 'Support', name: 'Support — Canned Reply Updated', value: 'support.canned_reply.updated' },
  { family: 'Support', name: 'Support — Conversation Assigned', value: 'support.conversation.assigned' },
  { family: 'Support', name: 'Support — Conversation Blocked', value: 'support.conversation.blocked' },
  { family: 'Support', name: 'Support — Conversation Opened', value: 'support.conversation.opened' },
  { family: 'Support', name: 'Support — Conversation Reopened', value: 'support.conversation.reopened' },
  { family: 'Support', name: 'Support — Conversation Resolved', value: 'support.conversation.resolved' },
  { family: 'Support', name: 'Support — Conversation Unblocked', value: 'support.conversation.unblocked' },
  { family: 'Support', name: 'Support — Message Received', value: 'support.message.received' },
  { family: 'Support', name: 'Support — Message Sent', value: 'support.message.sent' },
  { family: 'Support', name: 'Support — Settings Updated', value: 'support.settings.updated' },
  { family: 'Team', name: 'Team — Created', value: 'team.created' },
  { family: 'Team', name: 'Team — Deleted', value: 'team.deleted' },
  { family: 'Team', name: 'Team — Updated', value: 'team.updated' },
  { family: 'Team Member', name: 'Team Member — Invited', value: 'team.member.invited' },
  { family: 'Team Member', name: 'Team Member — Joined', value: 'team.member.joined' },
  { family: 'Team Member', name: 'Team Member — Removed', value: 'team.member.removed' },
  { family: 'Team Member', name: 'Team Member — Role Changed', value: 'team.member.role_changed' },
] as const;

export type SubscribyEvent = typeof EVENT_CATALOG[number]['value'];
export type SubscribyEventFamily = typeof EVENT_CATALOG[number]['family'];
